import os
import xml.etree.ElementTree as ET

def find_file_recursively_precise(root_directory):
    """
    Finds the exact XML files for 1 Chronicles 16 and Psalm 96, 
    ensuring 2 Chronicles is bypassed.
    """
    chron_match = None
    psalm_match = None
    
    for dirpath, _, filenames in os.walk(root_directory):
        for filename in filenames:
            if filename.lower().endswith('.xml'):
                fn_lower = filename.lower()
                
                # Strict check for 1 Chronicles or I Chronicles or 1_chronicles
                # Excludes 2 Chronicles explicitly
                is_chronicles = "chronicles" in fn_lower or "chron" in fn_lower
                is_first_book = "1" in fn_lower or "i" in fn_lower and "2" not in fn_lower
                if is_chronicles and is_first_book and "16" in fn_lower:
                    chron_match = os.path.join(dirpath, filename)
                    
                # Match Psalm 96
                if ("psalm" in fn_lower or "ps" in fn_lower) and "96" in fn_lower:
                    psalm_match = os.path.join(dirpath, filename)
                    
    return chron_match, psalm_match

def extract_melody_from_musicxml(xml_path, start_verse=None, end_verse=None):
    """
    Parses a MusicXML file. If start_verse and end_verse are provided,
    it slices the musical notes to only return the sequence within those boundaries.
    """
    if not xml_path or not os.path.exists(xml_path):
        return None
        
    try:
        tree = ET.parse(xml_path)
        root = tree.getroot()
        
        notes_sequence = []
        current_verse = 1  # Default fallback marker
        
        # Scan through measures sequentially
        for measure in root.findall(".//measure"):
            
            # Check if this measure explicitly declares a new verse number
            # Look inside lyric text or direction landmarks commonly generated by database dumps
            for lyric in measure.findall(".//lyric/text"):
                if lyric.text and lyric.text.isdigit():
                    current_verse = int(lyric.text)
            
            # Alternative layout check: look for verse markers in measure attributes/numbers
            measure_num = measure.get('number')
            if measure_num and measure_num.isdigit():
                # If your database structure maps 1 measure = 1 verse, we track it here
                current_verse = int(measure_num)

            # If constraints are active, skip notes outside our target sandbox
            if start_verse and current_verse < start_verse:
                continue
            if end_verse and current_verse > end_verse:
                continue
                
            # Process and collect notes inside this valid measure window
            for note in measure.findall(".//note"):
                if note.find("rest") is not None:
                    continue
                    
                pitch = note.find("pitch")
                if pitch is not None:
                    step = pitch.find("step").text
                    
                    # Check for accidental sharps or flats
                    accidental_element = note.find("accidental")
                    accidental = ""
                    if accidental_element is not None:
                        if accidental_element.text == "sharp":
                            accidental = "#"
                        elif accidental_element.text == "flat":
                            accidental = "b"
                            
                    notes_sequence.append(f"{step.lower()}{accidental}")
                    
        return notes_sequence
    except Exception as e:
        print(f"  [Error] Parsing failed for {os.path.basename(xml_path)}: {e}")
        return None

def run_system_comparison():
    print("=" * 85)
    print("CANONICAL SLICED COMPARISON ENGINE: 1 CHRONICLES 16:23-33 VS. FULL PSALM 96")
    print("=" * 85)
    
    script_dir = os.path.dirname(os.path.abspath(__file__))
    parent_dir = os.path.dirname(script_dir)
    
    # 1. Locate the precise files
    chronicles_path, psalm_path = find_file_recursively_precise(parent_dir)
    
    if not chronicles_path or not psalm_path:
        print("\n[Warning] File matching failed!")
        print("Could not find the target XML files inside any of the subfolders.")
        return

    print(f"[Success] Localized target assets:")
    print(f" -> Prose Base:   {os.path.relpath(chronicles_path, parent_dir)}")
    print(f" -> Poetic Base:  {os.path.relpath(psalm_path, parent_dir)}")
    
    print("\nExtracting constrained note arrays from MusicXML databases...")
    
    # Slice 1 Chronicles 16 strictly between verses 23 and 33
    chronicles_notes = extract_melody_from_musicxml(chronicles_path, start_verse=23, end_verse=33)
    # Psalm 96 is analyzed in full as the complete comparative template
    psalm_notes = extract_melody_from_musicxml(psalm_path)
    
    if not chronicles_notes or not psalm_notes:
        print("\n[Error] Empty data pool extracted from matched files.")
        return

    print("\n" + "-" * 50)
    print("CONSTRAINED MELODIC COMPREHENSIVE PROFILES")
    print("-" * 50)
    print(f"Total notes played in 1 Chronicles 16 (Verses 23-33) : {len(chronicles_notes)}")
    print(f"Total notes played in Full Psalm 96                 : {len(psalm_notes)}")
    
    print("\n" + "-" * 50)
    print("OPENING MOTIF COMPARISON (First 20 notes of selection)")
    print("-" * 50)
    print(f"Prose Section (1 Chron 16:23+) : {' '.join(chronicles_notes[:20])}")
    print(f"Poetry Score  (Psalm 96:1+)    : {' '.join(psalm_notes[:20])}")
    
    print("\n" + "-" * 50)
    print("MODAL ACCIDENTAL ACCUMULATION SCAN (Slicing Windows)")
    print("-" * 50)
    print(f"Prose Section -> Total sharps (#): {chronicles_notes.count('f#') + chronicles_notes.count('g#')}")
    print(f"Poetry Score  -> Total sharps (#): {psalm_notes.count('f#') + psalm_notes.count('g#')}")
    print("\n" + "=" * 85)

if __name__ == "__main__":
    run_system_comparison()
